### ISSUE TITLE
Use java.util.SecureRandom for improved random number generation

### ISSUE THREAD

**Issue by fkoehler** [kolotaev/ride#1]
Wouldn't it be better to use `java.util.SecureRandom` and on linux in combination with `-Djava.security.egd=file:/dev/./urandom` in order to improve the random numbers being generated. I also undestood that the default Random implementation runs into blocking easier if there are a lot of random numbers being requested

**Comment by kolotaev** [comment]
Hi @fkoehler, actually the main upside of SecureRandom is that it makes it impossible to predict the next random number from a sequence, which is good for security but is somehow irrelevant to the GUID's purpose, I guess. Meanwhile AFAIK SecureRandom carries on some performance penalty. See, for example, [in this article](http://www.mattnworb.com/post/the-dangers-of-java-security-securerandom/).
What do you think?

**Comment by fkoehler** [comment]
I am not an expert on this. AFAIK the performance issue can be overcome by
using /dev/urandom.

But if you think for this GUID purpose the normal on is good enough I think
we can leave it out then.

Am 15.02.2018 7:35 nachm. schrieb "Egor Kolotaev" <notifications@github.com
