### ISSUE TITLE
Find new hosting for releases.

### ISSUE THREAD

**Issue by Milyardo** [kolotaev/ride#11]
On May 1st, [jcenter and bintray will be sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), this project needs a new host for releases.

**Comment by kolotaev** [comment]
Thanks for the notice!
The notification about the sunset of the bintray has been lost somewhere in the mail.

I'll take a look at the issue asap.
I think maven central would be ok.

**Comment by kolotaev** [comment]
Published all existing releases to the MavenCentral.
Updated docs:  https://github.com/kolotaev/ride/pull/12
