### ISSUE TITLE
Two Id instances built from same string are not considered equal

### ISSUE THREAD

**Issue by fkoehler** [kolotaev/ride#2]
How to reproduce:

```
scala> Id("b9tgdaa0vejqu6es2db0") == Id("b9tgdaa0vejqu6es2db0")
res3: Boolean = false
```

**Comment by kolotaev** [comment]
Yeh, we can consider this as a buggy behavior in the expected context and semantics of Ids.
Fixed in https://github.com/kolotaev/ride/pull/4 by @fkoehler
